import { Inter } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "@/context/firstContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-center mt-10 text-2xl font-semibold">
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
